Product categories
Diogo1080/TresBrinde-Fe pull request #17
Opened 2023-05-17 18:50 UTC by Adan0k

2023-05-18 09:09 UTC, Gabriel-Sous-a requested changes

2023-05-18 09:09 UTC, Gabriel-Sous-a commented on src/images/roupa.png
pq q trocaste as imagens?

2023-05-18 09:09 UTC, Gabriel-Sous-a commented on src/pages/home/components/ProductCategories/index.tsx
> +  ];
Isto nao era suposto estar no ficheiro JSON?

2023-05-18 09:11 UTC, Gabriel-Sous-a requested changes

2023-05-18 09:11 UTC, Gabriel-Sous-a commented on src/pages/home/components/ProductCategories/index.tsx
> +  ];
Isto nao era suposto estar no ficheiro JSON?

2023-05-18 09:16 UTC, Adan0k commented on src/pages/home/components/ProductCategories/index.tsx
> +  ];
sim não num .json mas num js a parte

2023-05-18 09:29 UTC, Adan0k commented on src/images/roupa.png
como assim?

2023-05-18 09:30 UTC, Adan0k commented on src/images/roupa.png
ah

2023-05-18 09:31 UTC, Adan0k commented on src/images/roupa.png
quando eu estava tentando arranjar as imagens eu troquei pra ver se o problema não era a imagem

2023-05-18 13:55 UTC, LeoHabs requested changes
- Acho que as colunas deviam ser sempre 3 independentemente da largura do ecrã. Quando os cards precisarem de ir para a fila de baixo também deveriam alinhar à esquedas, e não ao centro.
- Quanto às imagens, tens na tua base de dados imagens?

2023-05-18 13:55 UTC, LeoHabs requested changes
- Acho que as colunas deviam ser sempre 3 independentemente da largura do ecrã. Quando os cards precisarem de ir para a fila de baixo também deveriam alinhar à esquedas, e não ao centro.
- Quanto às imagens, tens na tua base de dados imagens?

2023-05-18 14:51 UTC, Gabriel-Sous-a commented
O botao de "Ver produto" nao devia direcionar te para a pagina dos produtos?

2023-05-18 14:52 UTC, Gabriel-Sous-a requested changes

2023-05-18 14:52 UTC, Gabriel-Sous-a commented on src/components/category/categoryCard.tsx
> +      <button>Ver Produtos</button>
Nao devia direcionar te para a pagina dos produtos?

2023-05-19 09:00 UTC, Gabriel-Sous-a reviewed
Quando clicas no botao para ser direcionado para a pagina dos produtos da categoria o user devia ser posto sempre na parte de cima da pagina, e o botao no mobile para dar scroll entre categorias devias ter a funcionabilidade de onHold aquilo dar scroll

2023-05-19 09:02 UTC, Gabriel-Sous-a commented
E o sub header na tua branch nao esta bem formatado

2023-05-19 14:52 UTC, Gabriel-Sous-a approved these changes

2023-05-19 14:55 UTC, LeoHabs approved these changes

2023-05-19 14:56 UTC, merged