Subheader created
Diogo1080/TresBrinde-Fe pull request #3
Opened 2022-06-02 15:40 UTC by AFaioes

Subheader created, but needs to be updated...

2022-06-02 17:07 UTC, Diogo1080 requested changes
Remember to clean the code up. 🧹

2022-06-02 17:07 UTC, Diogo1080 commented on src/components/common/SubHeader/index.tsx
> +          </ul></>
This should be cleaned up.

Maybe some indentations?

2022-06-03 09:18 UTC, Diogo1080 approved these changes
All cleaned up 👍

2022-06-03 09:29 UTC, mariajoaomorais approved these changes
ok!

2022-06-03 09:30 UTC, merged