Fix subheader
Diogo1080/TresBrinde-Fe pull request #30
Opened 2023-05-24 11:46 UTC by LeoHabs

Fixed the white space wrapping

2023-05-24 12:44 UTC, Gabriel-Sous-a commented on src/redux/actions/BudgetActions.ts
> +      console.log(newData);
sneaky console.log

2023-05-24 12:45 UTC, Gabriel-Sous-a commented on src/redux/actions/BudgetActions.ts
> +      console.log(newData);
```suggestion
      
```

sneaky

2023-05-24 15:48 UTC, Adan0k requested changes
tu ta fazendo pr pra main

2023-05-24 18:33 UTC, Adan0k approved these changes
tu ta fazendo pr pra main

2023-05-25 08:49 UTC, Gabriel-Sous-a approved these changes

2023-05-25 08:50 UTC, merged