Budget
Diogo1080/TresBrinde-Fe pull request #38
Opened 2023-05-26 17:33 UTC by Adan0k

budget page created and styled

2023-05-29 08:18 UTC, Gabriel-Sous-a commented
<img width="1132" alt="Captura de ecrã 2023-05-29, às 09 18 05" src="https://github.com/mindera-school/TresBrinde-Fe/assets/116306408/09aabec3-febf-4b25-a59f-ed95641a9743">
Isto nao era suposto caber 3 produtos antes de ter overflow?

2023-05-29 08:19 UTC, Gabriel-Sous-a commented
<img width="1126" alt="Captura de ecrã 2023-05-29, às 09 19 07" src="https://github.com/mindera-school/TresBrinde-Fe/assets/116306408/e2ae7d6e-d1e3-4a54-ba82-144ad18b6f00">
o espaçamento esta estranho

2023-05-29 08:19 UTC, Gabriel-Sous-a commented
<img width="1125" alt="Captura de ecrã 2023-05-29, às 09 19 36" src="https://github.com/mindera-school/TresBrinde-Fe/assets/116306408/c1b44a68-bf6b-4843-a9f3-9bd07127372d">
falta padding em todos os inputs

2023-05-29 08:20 UTC, Gabriel-Sous-a commented
<img width="243" alt="Captura de ecrã 2023-05-29, às 09 20 06" src="https://github.com/mindera-school/TresBrinde-Fe/assets/116306408/441878bc-0fce-46e1-a552-663ad2309c5d">
Alem do botao "Cancelar" estar com letra minuscula falta espaço entre os botoes

2023-05-29 08:22 UTC, Gabriel-Sous-a requested changes

2023-05-29 08:22 UTC, Gabriel-Sous-a commented on src/pages/budget/components/BudgetForm/index.tsx
> +        <a href="/">cancelar</a>
```suggestion
        <a href="/">Cancelar</a>
```

2023-05-29 14:39 UTC, Gabriel-Sous-a commented
<img width="699" alt="Captura de ecrã 2023-05-29, às 15 38 18" src="https://github.com/mindera-school/TresBrinde-Fe/assets/116306408/e748a8f4-9f2f-4f0f-a439-1a9bd448cee6">
isto nao devia estar antes assim?
<img width="680" alt="Captura de ecrã 2023-05-29, às 15 38 41" src="https://github.com/mindera-school/TresBrinde-Fe/assets/116306408/028b3dee-3ddb-40e9-aa3b-ac5214bc8954">

2023-05-29 14:39 UTC, Gabriel-Sous-a commented
<img width="689" alt="Captura de ecrã 2023-05-29, às 15 39 20" src="https://github.com/mindera-school/TresBrinde-Fe/assets/116306408/e959d05a-cd66-4cdf-88c2-4888f2c21f79">
Além de estar com letra minuscula falta padding

2023-05-29 14:40 UTC, Gabriel-Sous-a commented
<img width="706" alt="Captura de ecrã 2023-05-29, às 15 39 50" src="https://github.com/mindera-school/TresBrinde-Fe/assets/116306408/8ff1d5de-42a4-4639-9623-b3427110abd1">
tenta ser consistente com o portugues, no design tratam o utilizador por "tu" nao acho q faça muito sentido

2023-05-31 10:11 UTC, Gabriel-Sous-a approved these changes

2023-05-31 10:12 UTC, Rocha1313 approved these changes

2023-05-31 11:58 UTC, LeoHabs commented
![image](https://github.com/mindera-school/TresBrinde-Fe/assets/117355219/fb3c8db4-3258-4072-9ff7-5cfa8143b4d6)

Acho que fica msm péssimo aquele "Teu nome", não acho que fique fixe tratar por tu e o "Confirma a tua morada" acho que devia ser só Morada ou o exemplo de uma rua, o "Adiciona uma mensagem" segue a msm cena que disse no inicio i guess

2023-05-31 14:33 UTC, Gabriel-Sous-a commented
<img width="1005" alt="Captura de ecrã 2023-05-31, às 15 33 21" src="https://github.com/mindera-school/TresBrinde-Fe/assets/116306408/4d4b1bad-3fb2-42f8-b3bd-97d0c5693b75">
o produto "table" nao tinha nem cor nem tamanho e ficou com isso de outro produto

2023-05-31 14:35 UTC, Gabriel-Sous-a commented
<img width="1680" alt="Captura de ecrã 2023-05-31, às 15 34 45" src="https://github.com/mindera-school/TresBrinde-Fe/assets/116306408/b16870de-409d-4748-8e19-b9884bae19db">
podes reduzir um bocado o tamanho da pagina depois dos botoes

2023-05-31 14:35 UTC, Gabriel-Sous-a requested changes

2023-05-31 14:35 UTC, Gabriel-Sous-a commented on src/pages/budget/components/BudgetForm/index.tsx
> +            placeholder="0000000"
```suggestion
            placeholder="0000-000"
```

2023-05-31 14:36 UTC, Gabriel-Sous-a approved these changes

2023-05-31 14:36 UTC, Gabriel-Sous-a commented on src/pages/budget/components/BudgetForm/index.tsx
> +          placeholder="Adiciona uma mensagem ao pedido"
```suggestion
          placeholder="Adicione uma mensagem ao pedido"
```

2023-05-31 14:36 UTC, Gabriel-Sous-a commented on src/pages/budget/components/BudgetForm/index.tsx
> +            placeholder="Confirma a morada"
```suggestion
            placeholder="Confirme a morada"
```

2023-05-31 14:48 UTC, Gabriel-Sous-a approved these changes

2023-05-31 14:55 UTC, LeoHabs approved these changes

2023-05-31 14:56 UTC, merged